# Generated by Django 5.0.1 on 2024-11-11 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='account_number',
            new_name='user',
        ),
    ]
